# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - rm87537-Ecommerce

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_7e57160398c64b6292e9a8e06cc19e36 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_da7d4776bc25450ba29afac98c33a211 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_7e57160398c64b6292e9a8e06cc19e36 }}/ecommerce:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'rm87537-Ecommerce'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6eeacbc20dca4f46a2d0f76013c5442c }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_7e57160398c64b6292e9a8e06cc19e36 }}/ecommerce:${{ github.sha }}'